# Book settings
title: An Introduction to "AI" in My Opinion
author: Julie / jewels2001
# logo: olympics.png

html:
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: false
  baseurl: https://olymvis-jupyterbook.hongtaoh.com/

repository:
  url: https://github.com/jewels2001/ai-book1
  branch: master



